/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "brand-light-gray": "#F5F7FA",
        "brand-card-gray": "#F9FAFB",
        "brand-dark-blue": "#004499",
        "tertiary": "#745b00",
        "electric-blue": "#0055AA",
        "surface-tint": "#165db2",
        "surface-container": "#eceef1",
        "on-primary": "#ffffff",
        "surface": "#f7f9fc",
        "success-green": "#28A745",
        "surface-bright": "#f7f9fc",
        "on-primary-fixed": "#001b3e",
        "surface-variant": "#e0e3e6",
        "primary-container": "#0055aa",
        "primary-fixed-dim": "#aac7ff",
        "surface-container-highest": "#e0e3e6",
        "safety-yellow": "#FFCC00",
        "on-secondary": "#ffffff",
        "secondary-container": "#9fc2fe",
        "on-surface-variant": "#424752",
        "primary": "#003e7f",
        "on-background": "#191c1e",
        "deep-navy": "#003366",
        "inverse-on-surface": "#eff1f4",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#1f477b",
        "outline-variant": "#c2c6d4",
        "secondary-fixed": "#d5e3ff",
        "on-primary-fixed-variant": "#00458d",
        "tertiary-container": "#d0a600",
        "tertiary-fixed": "#ffe08b",
        "on-tertiary-fixed-variant": "#584400",
        "on-error-container": "#93000a",
        "primary-fixed": "#d6e3ff",
        "surface-dim": "#d8dadd",
        "on-primary-container": "#b3cdff",
        "inverse-surface": "#2d3133",
        "background": "#f7f9fc",
        "inverse-primary": "#aac7ff",
        "emergency-red": "#CC0000",
        "on-tertiary-fixed": "#241a00",
        "on-secondary-container": "#294f83",
        "outline": "#727783",
        "surface-subtle": "#F9FAFB",
        "surface-container-high": "#e6e8eb",
        "secondary": "#3a5f94",
        "on-tertiary-container": "#4f3d00",
        "secondary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed": "#001b3c",
        "tertiary-fixed-dim": "#f1c100",
        "surface-container-low": "#f2f4f7",
        "on-error": "#ffffff",
        "on-surface": "#191c1e"
      },
      spacing: {
        "base": "8px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Open Sans", "sans-serif"],
        "label-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Open Sans", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
